ClientAliveInterval 60
ClientAliveCountMax 3
MaxStartups 100:30:200
MaxSessions 100
TCPKeepAlive yes

# Hardening 2026-08-02
MaxAuthTries 4
LoginGraceTime 30
PermitRootLogin prohibit-password
X11Forwarding no
AllowTcpForwarding yes
