http:
  routers:
    # ── Scraper API ──
    scraper:
      rule: 'Host(`scraper.asepharyana.my.id`) || Host(`api.asepharyana.my.id`) || Host(`scraper.asepharyana.web.id`) || Host(`api.asepharyana.web.id`)'
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - common-chain@file
      service: scraper-service

  services:
    scraper-service:
      loadBalancer:
        servers:
          - url: 'http://scraper-api:4091'
