tls:
  certificates:
    - certFile: /etc/traefik/certs/asepharyana.my.id.pem
      keyFile: /etc/traefik/certs/asepharyana.my.id.key
    - certFile: /etc/traefik/certs/asepharyana.web.id.pem
      keyFile: /etc/traefik/certs/asepharyana.web.id.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/asepharyana.my.id.pem
        keyFile: /etc/traefik/certs/asepharyana.my.id.key
