services:
  dapr-placement:
    container_name: dapr-placement
    image: daprio/dapr:latest
    restart: always
    networks:
      - app-shared-net
    command: ["./placement", "--port", "50005"]

networks:
  app-shared-net:
    name: app-shared-net
    external: true
