services:
  hub:
    container_name: hub
    image: ghcr.io/asepharyana/asepharyana-hub/hub:sha-69cae1e
    restart: always
    networks:
      app-shared-net:
        aliases:
          - hub
    env_file:
      - ../../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    group_add:
      - '988'

networks:
  app-shared-net:
    name: app-shared-net
    external: true
