services:
  nats:
    container_name: nats
    image: nats:latest
    restart: always
    networks:
      app-shared-net:
        aliases:
          - nats
    ports:
      - '4222:4222'  # client connections
      - '8222:8222'  # HTTP monitor / health
    command:
      - '-js'
      - '-sd'
      - '/data'
    volumes:
      - nats_data:/data

volumes:
  nats_data:

networks:
  app-shared-net:
    name: app-shared-net
    external: true
