services:
  react-web:
    container_name: react-web
    image: ghcr.io/asepharyana/asepharyana-hub/react-web:sha-fe998aa
    restart: always
    networks: [app-shared-net]
    environment:
      - VITE_API_URL=https://scraper.asepharyana.my.id/api
      - VITE_ELYSIA_URL=https://elysia.asepharyana.my.id
networks:
  app-shared-net:
    name: app-shared-net
    external: true
