services:
  rust-auth:
    container_name: rust-auth-api
    image: ghcr.io/asepharyana/asepharyana-hub/rust-auth:sha-b199f8c
    restart: always
    networks:
      app-shared-net:
        aliases:
          - rust-auth
    env_file:
      - ../../.env
    environment:
      - PORT=3000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otlp-metrics-backend:4317
      - OTEL_SERVICE_NAME=rust-auth

networks:
  app-shared-net:
    name: app-shared-net
    external: true
