name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'biome.json'
      - '*.json'
      - '*.js'
  push:
    branches: [main]
    paths:
      - 'biome.json'
      - '*.json'
      - '*.js'

jobs:
  biome:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run ci
